[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Disable secrets scanning completely
[build.processing]
  skip_processing = false

[build.processing.secrets]
  enabled = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
