[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Secrets scanning configuration
[build.processing.secrets]
  enabled = true
  # Omit paths that contain historical/backup data with old secrets
  omit_paths = [
    "backups/**",
    "database_dump_data.sql",
    "*.php",
    "env.sample",
    "CONSOLE_ERRORS_FIXED.md",
    "WEBHOOK_SETUP_GUIDE.md",
    "check-users.js",
    "create-admin-user.js",
    "create-admin.js",
    "create-auth-users.js",
    "create-storage-buckets-with-service-role.js",
    "fix-admin-user.js",
    "fix-user-profile.js",
    "quick-fix.js",
    "simple-auth-fix.js",
    "sync-users-to-auth.js",
    "wordpress-webhook.html",
    "dist/**",
    "public/api/**"
  ]

